language: node_js

# latest stable Node.js release is pointed by "node" version number
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - yarn install

script:
  # - ng test --single-run
  # temporarly disabled e2e tests till full configuration of HAProxy
  # - docker-compose --file docker-compose-ci.yml up &
  # - ng build
  # - ng serve &
  # - sleep 60 # waits for services
  # - ng e2e

- ng build --prod --aot

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "posesor-condo-fees-poc"
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
